Update patch set 1
Patch Set 1: Code-Review+1

why -2 ?
fix my ims.apk issue

 03-04 15:33:19.254  5831  5831 E QImsService: ImsServiceSub : [0] IMS Service Status Update failed!
03-04 15:33:19.255  5831  5831 E QImsService: ImsConfigImpl : onSubscriptionsChanged unable to process due to SubscriptionInfo is null
03-04 15:33:19.255  5831  5831 E QImsService: ImsServiceSub : [1] IMS Service Status Update failed!
03-04 15:33:19.268  5831  5831 E AndroidRuntime: FATAL EXCEPTION: main
03-04 15:33:19.268  5831  5831 E AndroidRuntime: Process: org.codeaurora.ims, PID: 5831
03-04 15:33:19.268  5831  5831 E AndroidRuntime: java.lang.NoSuchMethodError: No static method getAutoReject(Landroid/content/ContentResolver;I)I in class Lorg/codeaurora/ims/utils/QtiImsExtUtils; or its super classes (declaration of 'org.codeaurora.ims.utils.QtiImsExtUtils' appears in /product/framework/ims-ext-common.jar)
03-04 15:33:19.268  5831  5831 E AndroidRuntime:        at org.codeaurora.ims.ImsServiceSub.onStackConfigChanged(ImsServiceSub.java:446)
03-04 15:33:19.268  5831  5831 E AndroidRuntime:        at org.codeaurora.ims.ImsSubController.notifyStackConfigChanged(ImsSubController.java:237)
03-04 15:33:19.268  5831  5831 E AndroidRuntime:        at org.codeaurora.ims.ImsSubController.handleSubConfigChanged(ImsSubController.java:274)
03-04 15:33:19.268  5831  5831 E AndroidRuntime:        at org.codeaurora.ims.ImsSubController.access$100(ImsSubController.java:37)
03-04 15:33:19.268  5831  5831 E AndroidRuntime:        at org.codeaurora.ims.ImsSubController$ImsSubControllerHandler.handleMessage(ImsSubController.java:305)
03-04 15:33:19.268  5831  5831 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
03-04 15:33:19.268  5831  5831 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
03-04 15:33:19.268  5831  5831 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7701)
03-04 15:33:19.268  5831  5831 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-04 15:33:19.268  5831  5831 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
03-04 15:33:19.268  5831  5831 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
03-04 15:33:19.313  1552  3524 E ActivityManager: Service ServiceRecord{b4d5f58 u0 org.codeaurora.ims/.ImsService} in process ProcessRecord{3b70634 5831:org.codeaurora.ims/u0a0} not same as in map: ServiceRecord{d7c34e9 u0 org.codeaurora.ims/.ImsService}

Patch-set: 1
Reviewer: Gerrit User 1002322 <1002322@56841c99-7c94-43d4-bf0b-cb4707e66d55>
Label: Code-Review=+1